[2020-06-22 12:08:47,581] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagindag.testairflow 2020-06-22T12:07:53.494673+00:00 [queued]>
[2020-06-22 12:08:47,589] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagindag.testairflow 2020-06-22T12:07:53.494673+00:00 [queued]>
[2020-06-22 12:08:47,589] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-22 12:08:47,589] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-22 12:08:47,589] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-22 12:08:47,599] {taskinstance.py:900} INFO - Executing <Task(BashOperator): testairflow> on 2020-06-22T12:07:53.494673+00:00
[2020-06-22 12:08:47,601] {standard_task_runner.py:53} INFO - Started process 6436 to run task
[2020-06-22 12:08:47,681] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagindag.testairflow 2020-06-22T12:07:53.494673+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-22 12:08:47,694] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-22 12:08:47,697] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpkggZE8/testairfloweSRRup
[2020-06-22 12:08:47,697] {bash_operator.py:115} INFO - Running command: python /home/ec2-user/airflow/dags/hell.py fun() 
[2020-06-22 12:08:47,702] {bash_operator.py:122} INFO - Output:
[2020-06-22 12:08:47,710] {bash_operator.py:126} INFO - /tmp/airflowtmpkggZE8/testairfloweSRRup: line 1: syntax error near unexpected token `('
[2020-06-22 12:08:47,711] {bash_operator.py:126} INFO - /tmp/airflowtmpkggZE8/testairfloweSRRup: line 1: `python /home/ec2-user/airflow/dags/hell.py fun() '
[2020-06-22 12:08:47,711] {bash_operator.py:130} INFO - Command exited with return code 2
[2020-06-22 12:08:47,721] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2020-06-22 12:08:47,728] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dagindag, task_id=testairflow, execution_date=20200622T120753, start_date=20200622T120847, end_date=20200622T120847
[2020-06-22 12:08:57,578] {logging_mixin.py:112} INFO - [2020-06-22 12:08:57,578] {local_task_job.py:103} INFO - Task exited with return code 1
