[2020-06-23 12:09:01,244] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slacks_variable.testslackbash 2020-06-23T12:07:52.437554+00:00 [queued]>
[2020-06-23 12:09:01,251] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slacks_variable.testslackbash 2020-06-23T12:07:52.437554+00:00 [queued]>
[2020-06-23 12:09:01,251] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 12:09:01,251] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-23 12:09:01,251] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 12:09:01,262] {taskinstance.py:900} INFO - Executing <Task(BashOperator): testslackbash> on 2020-06-23T12:07:52.437554+00:00
[2020-06-23 12:09:01,264] {standard_task_runner.py:53} INFO - Started process 4266 to run task
[2020-06-23 12:09:01,319] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: slacks_variable.testslackbash 2020-06-23T12:07:52.437554+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-23 12:09:01,368] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-23 12:09:01,370] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpYhmWgI/testslackbashwyAI6E
[2020-06-23 12:09:01,371] {bash_operator.py:115} INFO - Running command: python /home/ec2-user/airflow/dags/hell.py anithabucket
[2020-06-23 12:09:01,374] {bash_operator.py:122} INFO - Output:
[2020-06-23 12:09:01,763] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-06-23 12:09:01,763] {bash_operator.py:126} INFO -   File "/home/ec2-user/airflow/dags/hell.py", line 1, in <module>
[2020-06-23 12:09:01,763] {bash_operator.py:126} INFO -     from airflow.models import Variable
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/__init__.py", line 42, in <module>
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -     from airflow.models import DAG
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/__init__.py", line 21, in <module>
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -     from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/baseoperator.py", line 43, in <module>
[2020-06-23 12:09:01,764] {bash_operator.py:126} INFO -     from airflow.models.dag import DAG
[2020-06-23 12:09:01,765] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/dag.py", line 55, in <module>
[2020-06-23 12:09:01,765] {bash_operator.py:126} INFO -     from airflow.models.taskinstance import TaskInstance, clear_task_instances
[2020-06-23 12:09:01,765] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 61, in <module>
[2020-06-23 12:09:01,765] {bash_operator.py:126} INFO -     from airflow.utils.email import send_email
[2020-06-23 12:09:01,765] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/utils/email.py", line 33, in <module>
[2020-06-23 12:09:01,766] {bash_operator.py:126} INFO -     import smtplib
[2020-06-23 12:09:01,766] {bash_operator.py:126} INFO -   File "/usr/lib64/python2.7/smtplib.py", line 46, in <module>
[2020-06-23 12:09:01,766] {bash_operator.py:126} INFO -     import email.utils
[2020-06-23 12:09:01,766] {bash_operator.py:126} INFO -   File "/home/ec2-user/airflow/dags/email.py", line 2, in <module>
[2020-06-23 12:09:01,766] {bash_operator.py:126} INFO -     from airflow import DAG
[2020-06-23 12:09:01,767] {bash_operator.py:126} INFO - ImportError: cannot import name DAG
[2020-06-23 12:09:01,787] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-06-23 12:09:01,793] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2020-06-23 12:09:01,794] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=slacks_variable, task_id=testslackbash, execution_date=20200623T120752, start_date=20200623T120901, end_date=20200623T120901
[2020-06-23 12:09:11,238] {logging_mixin.py:112} INFO - [2020-06-23 12:09:11,238] {local_task_job.py:103} INFO - Task exited with return code 1
