[2020-06-17 13:32:08,418] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: S3.dummy_start 2020-06-17T13:30:50.673937+00:00 [queued]>
[2020-06-17 13:32:08,425] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: S3.dummy_start 2020-06-17T13:30:50.673937+00:00 [queued]>
[2020-06-17 13:32:08,425] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 13:32:08,425] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-17 13:32:08,426] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 13:32:08,434] {taskinstance.py:900} INFO - Executing <Task(DummyOperator): dummy_start> on 2020-06-17T13:30:50.673937+00:00
[2020-06-17 13:32:08,436] {standard_task_runner.py:53} INFO - Started process 4884 to run task
[2020-06-17 13:32:08,492] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3.dummy_start 2020-06-17T13:30:50.673937+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-17 13:32:08,506] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=S3, task_id=dummy_start, execution_date=20200617T133050, start_date=20200617T133208, end_date=20200617T133208
[2020-06-17 13:32:18,416] {logging_mixin.py:112} INFO - [2020-06-17 13:32:18,416] {local_task_job.py:103} INFO - Task exited with return code 0
