[2020-06-23 07:53:11,899] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: variable_ex.testairflow 2020-06-23T07:52:30.598661+00:00 [queued]>
[2020-06-23 07:53:11,906] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: variable_ex.testairflow 2020-06-23T07:52:30.598661+00:00 [queued]>
[2020-06-23 07:53:11,907] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 07:53:11,907] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-23 07:53:11,907] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-23 07:53:11,917] {taskinstance.py:900} INFO - Executing <Task(BashOperator): testairflow> on 2020-06-23T07:52:30.598661+00:00
[2020-06-23 07:53:11,918] {standard_task_runner.py:53} INFO - Started process 3830 to run task
[2020-06-23 07:53:11,973] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: variable_ex.testairflow 2020-06-23T07:52:30.598661+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-23 07:53:11,985] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-23 07:53:11,986] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpU811xO/testairflow_xgGl_
[2020-06-23 07:53:11,987] {bash_operator.py:115} INFO - Running command: python /home/ec2-user/airflow/dags/hell.py 'example_variables_config'
[2020-06-23 07:53:11,990] {bash_operator.py:122} INFO - Output:
[2020-06-23 07:53:12,382] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-06-23 07:53:12,382] {bash_operator.py:126} INFO -   File "/home/ec2-user/airflow/dags/hell.py", line 1, in <module>
[2020-06-23 07:53:12,382] {bash_operator.py:126} INFO -     from airflow.models import Variable
[2020-06-23 07:53:12,382] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/__init__.py", line 42, in <module>
[2020-06-23 07:53:12,382] {bash_operator.py:126} INFO -     from airflow.models import DAG
[2020-06-23 07:53:12,383] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/__init__.py", line 21, in <module>
[2020-06-23 07:53:12,383] {bash_operator.py:126} INFO -     from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
[2020-06-23 07:53:12,383] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/baseoperator.py", line 43, in <module>
[2020-06-23 07:53:12,383] {bash_operator.py:126} INFO -     from airflow.models.dag import DAG
[2020-06-23 07:53:12,383] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/dag.py", line 55, in <module>
[2020-06-23 07:53:12,384] {bash_operator.py:126} INFO -     from airflow.models.taskinstance import TaskInstance, clear_task_instances
[2020-06-23 07:53:12,384] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 61, in <module>
[2020-06-23 07:53:12,384] {bash_operator.py:126} INFO -     from airflow.utils.email import send_email
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -   File "/usr/lib/python2.7/site-packages/airflow/utils/email.py", line 33, in <module>
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -     import smtplib
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -   File "/usr/lib64/python2.7/smtplib.py", line 46, in <module>
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -     import email.utils
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -   File "/home/ec2-user/airflow/dags/email.py", line 2, in <module>
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO -     from airflow import DAG
[2020-06-23 07:53:12,387] {bash_operator.py:126} INFO - ImportError: cannot import name DAG
[2020-06-23 07:53:12,408] {bash_operator.py:130} INFO - Command exited with return code 1
[2020-06-23 07:53:12,414] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2020-06-23 07:53:12,415] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=variable_ex, task_id=testairflow, execution_date=20200623T075230, start_date=20200623T075311, end_date=20200623T075312
[2020-06-23 07:53:21,896] {logging_mixin.py:112} INFO - [2020-06-23 07:53:21,896] {local_task_job.py:103} INFO - Task exited with return code 1
