[2020-06-17 13:31:45,931] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: S3.dummy_start 2019-01-01T00:00:00+00:00 [queued]>
[2020-06-17 13:31:45,938] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: S3.dummy_start 2019-01-01T00:00:00+00:00 [queued]>
[2020-06-17 13:31:45,938] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 13:31:45,938] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-17 13:31:45,938] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 13:31:45,948] {taskinstance.py:900} INFO - Executing <Task(DummyOperator): dummy_start> on 2019-01-01T00:00:00+00:00
[2020-06-17 13:31:45,950] {standard_task_runner.py:53} INFO - Started process 4869 to run task
[2020-06-17 13:31:46,007] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: S3.dummy_start 2019-01-01T00:00:00+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-17 13:31:46,020] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=S3, task_id=dummy_start, execution_date=20190101T000000, start_date=20200617T133145, end_date=20200617T133146
[2020-06-17 13:31:55,924] {logging_mixin.py:112} INFO - [2020-06-17 13:31:55,924] {local_task_job.py:103} INFO - Task exited with return code 0
