[2020-06-18 09:24:48,717] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [queued]>
[2020-06-18 09:24:48,724] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [queued]>
[2020-06-18 09:24:48,724] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 09:24:48,724] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-18 09:24:48,724] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 09:24:48,734] {taskinstance.py:900} INFO - Executing <Task(SlackWebhookOperator): slack_msg> on 2018-08-11T00:04:00+00:00
[2020-06-18 09:24:48,736] {standard_task_runner.py:53} INFO - Started process 10231 to run task
[2020-06-18 09:24:48,796] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-18 09:24:48,821] {taskinstance.py:1145} ERROR - Cannot get token: No valid Slack webhook token nor conn_id supplied
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/contrib/operators/slack_webhook_operator.py", line 111, in execute
    self.proxy
  File "/usr/lib/python2.7/site-packages/airflow/contrib/hooks/slack_webhook_hook.py", line 79, in __init__
    self.webhook_token = self._get_token(webhook_token, http_conn_id)
  File "/usr/lib/python2.7/site-packages/airflow/contrib/hooks/slack_webhook_hook.py", line 108, in _get_token
    raise AirflowException('Cannot get token: No valid Slack '
AirflowException: Cannot get token: No valid Slack webhook token nor conn_id supplied
[2020-06-18 09:24:48,829] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=slack_example, task_id=slack_msg, execution_date=20180811T000400, start_date=20200618T092448, end_date=20200618T092448
[2020-06-18 09:24:58,714] {logging_mixin.py:112} INFO - [2020-06-18 09:24:58,713] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-18 12:19:24,766] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [queued]>
[2020-06-18 12:19:24,774] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [queued]>
[2020-06-18 12:19:24,775] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 12:19:24,775] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-18 12:19:24,775] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 12:19:24,784] {taskinstance.py:900} INFO - Executing <Task(SlackWebhookOperator): slack_msg> on 2018-08-11T00:04:00+00:00
[2020-06-18 12:19:24,786] {standard_task_runner.py:53} INFO - Started process 5450 to run task
[2020-06-18 12:19:24,843] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: slack_example.slack_msg 2018-08-11T00:04:00+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-18 12:19:24,864] {logging_mixin.py:112} INFO - [2020-06-18 12:19:24,864] {base_hook.py:87} INFO - Using connection to: id: anitha_slack. Host: https://hooks.slack.com/services, Port: None, Schema: None, Login: None, Password: XXXXXXXX, extra: None
[2020-06-18 12:19:24,866] {logging_mixin.py:112} INFO - [2020-06-18 12:19:24,866] {http_hook.py:136} INFO - Sending 'POST' to url: https://hooks.slack.com/services/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
[2020-06-18 12:19:24,873] {logging_mixin.py:112} WARNING - /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[2020-06-18 12:19:24,888] {logging_mixin.py:112} INFO - [2020-06-18 12:19:24,888] {http_hook.py:150} ERROR - HTTP error: Bad Request
[2020-06-18 12:19:24,889] {logging_mixin.py:112} INFO - [2020-06-18 12:19:24,889] {http_hook.py:151} ERROR - no_text
[2020-06-18 12:19:24,892] {taskinstance.py:1145} ERROR - 400:Bad Request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/contrib/operators/slack_webhook_operator.py", line 113, in execute
    self.hook.execute()
  File "/usr/lib/python2.7/site-packages/airflow/contrib/hooks/slack_webhook_hook.py", line 152, in execute
    extra_options={'proxies': proxies})
  File "/usr/lib/python2.7/site-packages/airflow/hooks/http_hook.py", line 137, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/usr/lib/python2.7/site-packages/airflow/hooks/http_hook.py", line 181, in run_and_check
    self.check_response(response)
  File "/usr/lib/python2.7/site-packages/airflow/hooks/http_hook.py", line 152, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
AirflowException: 400:Bad Request
[2020-06-18 12:19:24,893] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=slack_example, task_id=slack_msg, execution_date=20180811T000400, start_date=20200618T121924, end_date=20200618T121924
[2020-06-18 12:19:34,765] {logging_mixin.py:112} INFO - [2020-06-18 12:19:34,765] {local_task_job.py:103} INFO - Task exited with return code 1
