[2020-06-18 06:07:14,033] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: example_variables.get_variable_value 2019-02-15T00:00:00+00:00 [queued]>
[2020-06-18 06:07:14,044] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: example_variables.get_variable_value 2019-02-15T00:00:00+00:00 [queued]>
[2020-06-18 06:07:14,044] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 06:07:14,044] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-18 06:07:14,044] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 06:07:14,054] {taskinstance.py:900} INFO - Executing <Task(BashOperator): get_variable_value> on 2019-02-15T00:00:00+00:00
[2020-06-18 06:07:14,056] {standard_task_runner.py:53} INFO - Started process 5796 to run task
[2020-06-18 06:07:14,114] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: example_variables.get_variable_value 2019-02-15T00:00:00+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-18 06:07:14,133] {taskinstance.py:1145} ERROR - 'Variable var3 does not exist'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/usr/lib/python2.7/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/usr/lib/python2.7/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/usr/lib/python2.7/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 1311, in __getattr__
    self.var = Variable.get(item)
  File "/usr/lib/python2.7/site-packages/airflow/models/variable.py", line 118, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable var3 does not exist'
[2020-06-18 06:07:14,148] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=example_variables, task_id=get_variable_value, execution_date=20190215T000000, start_date=20200618T060714, end_date=20200618T060714
[2020-06-18 06:07:24,027] {logging_mixin.py:112} INFO - [2020-06-18 06:07:24,026] {local_task_job.py:103} INFO - Task exited with return code 1
