[2020-06-18 12:19:48,574] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slackalert.coin_flip 2020-06-18T12:18:42.915976+00:00 [queued]>
[2020-06-18 12:19:48,582] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: slackalert.coin_flip 2020-06-18T12:18:42.915976+00:00 [queued]>
[2020-06-18 12:19:48,582] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 12:19:48,583] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-18 12:19:48,583] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 12:19:48,592] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): coin_flip> on 2020-06-18T12:18:42.915976+00:00
[2020-06-18 12:19:48,594] {standard_task_runner.py:53} INFO - Started process 5468 to run task
[2020-06-18 12:19:48,651] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: slackalert.coin_flip 2020-06-18T12:18:42.915976+00:00 [running]> ip-172-31-76-14.ec2.internal
[2020-06-18 12:19:48,662] {logging_mixin.py:112} INFO - Coin flipped heads. We win!
[2020-06-18 12:19:48,662] {python_operator.py:114} INFO - Done. Returned value was: True
[2020-06-18 12:19:48,678] {taskinstance.py:1047} ERROR - Failed when executing success callback
[2020-06-18 12:19:48,678] {taskinstance.py:1048} ERROR - The conn_id `snitha_slack` isn't defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/airflow/models/taskinstance.py", line 1045, in _run_raw_task
    task.on_success_callback(context)
  File "/home/ec2-user/airflow/dags/slack1alert.py", line 9, in task_success_slack_alert
    slack_webhook_token = BaseHook.get_connection(SLACK_CONN_ID).password
  File "/usr/lib/python2.7/site-packages/airflow/hooks/base_hook.py", line 84, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/lib/python2.7/site-packages/airflow/hooks/base_hook.py", line 80, in get_connections
    return secrets.get_connections(conn_id)
  File "/usr/lib/python2.7/site-packages/airflow/secrets/__init__.py", line 56, in get_connections
    raise AirflowException("The conn_id `{0}` isn't defined".format(conn_id))
AirflowException: The conn_id `snitha_slack` isn't defined
[2020-06-18 12:19:48,679] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=slackalert, task_id=coin_flip, execution_date=20200618T121842, start_date=20200618T121948, end_date=20200618T121948
[2020-06-18 12:19:58,571] {logging_mixin.py:112} INFO - [2020-06-18 12:19:58,571] {local_task_job.py:103} INFO - Task exited with return code 0
